stages:
  - test
  - documentation

before_script:
  # display centos version
  - cat /etc/issue
  # - git config user.email

  # Pull required packages
  - python3 -m pip install pytest pytest-cov

  # Get ConfigParserEnhanced
  # See https://pip.pypa.io/en/stable/reference/pip_install/#git : useful data on how to format this link
  #     https://stackoverflow.com/a/35998253/2059999 : also useful for some info on how to write the target
  - python3 -m pip uninstall -y configparserenhanced
  - python3 -m pip install --user git+https://gitlab+deploy-token-CI:${CI_GROUP_READ_TOKEN}@internal.gitlab.server/trilinos-devops-consolidation/code/ConfigParserEnhanced.git@master#egg=configparserenhanced
  # Methods that work on the command line but not in CI.
  # - python3 -m pip install --user -r requirements.txt

pytest:
  stage: test
  timeout: 20m
  script:
    #- bash ./exec-reqs-install.sh
    - python3 -m pytest --cov=setenvironment --cov-report html --cov-report term
  coverage: '/TOTAL\s*[0-9]*\s*[0-9]*\s*(\d+%)/'

sphinx-documentation:
  stage: test
  timeout: 20m
  script:
    - cd doc/
    - python3 -m pip install -r requirements.txt
    - bash make_html_docs.sh

publish coverage:
  stage: documentation
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - python3 -m pytest --cov=setenvironment --cov-report html --cov-report term
    - rm -rf /home/josbrau/html_files/SetEnvironmentNew/coverage
    - mkdir -p /home/josbrau/html_files/SetEnvironmentNew/coverage
    - mv tests/htmlcov/* /home/josbrau/html_files/SetEnvironmentNew/coverage/

publish docs:
  stage: documentation
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - cd doc/
    - python3 -m pip install -r requirements.txt
    - bash make_html_docs.sh
    - rm -rf /home/josbrau/html_files/SetEnvironmentNew/doc
    - mkdir -p /home/josbrau/html_files/SetEnvironmentNew/doc
    - mv html/* /home/josbrau/html_files/SetEnvironmentNew/doc/



